use_frameworks!

target 'DataSafeParser_Example' do
  pod 'DataSafeParser', :path => '../'

  target 'DataSafeParser_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
